# Setup
title: Crypto Mirror
tagline:
baseurl:  ""
paginate: 1

# About/contact
author:
name:
url:  https://github.com/crypto-mirror/cryptomirror

# Gems
gems:
  - jekyll-paginate

# Others
markdown: kramdown
